name: domine
description: Search domains with expressions. Insert numbers, letters, and any TLDs in one query.
version: 1.0.0+hotfix5
repository: https://github.com/breitburg/domine
issue_tracker: https://github.com/breitburg/domine/issues

topics:
- cli

environment:
  sdk: ^3.0.6

dependencies:
  args: ^2.4.2
  cli_spinner: ^1.0.4
  dart_openai: ^4.0.0
  http: ^1.1.0
  tint: ^2.0.1

dev_dependencies:
  lints: ^2.0.0

executables:
  domine:

platforms:
  macos:
  linux: